services:
  postgres:
    image: 'postgres:17-alpine'
    container_name: 'aid_postgres'
    environment:
      POSTGRES_DB: ${AID_DATABASE_NAME}
      POSTGRES_USER: ${AID_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${AID_DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AID_DATABASE_USERNAME} -d ${AID_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: