spring.application.name=id

# Database Settings
spring.datasource.url=${AID_DATABASE_URL}
spring.datasource.username=${AID_DATABASE_USERNAME}
spring.datasource.password=${AID_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway Settings
spring.flyway.enabled=true